/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PaintingsRouteImport } from './routes/paintings'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PaintingsSlugRouteImport } from './routes/paintings.$slug'

const PaintingsRoute = PaintingsRouteImport.update({
  id: '/paintings',
  path: '/paintings',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PaintingsSlugRoute = PaintingsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PaintingsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/paintings': typeof PaintingsRouteWithChildren
  '/paintings/$slug': typeof PaintingsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/paintings': typeof PaintingsRouteWithChildren
  '/paintings/$slug': typeof PaintingsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/paintings': typeof PaintingsRouteWithChildren
  '/paintings/$slug': typeof PaintingsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/contact' | '/paintings' | '/paintings/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/contact' | '/paintings' | '/paintings/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/paintings'
    | '/paintings/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  PaintingsRoute: typeof PaintingsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/paintings': {
      id: '/paintings'
      path: '/paintings'
      fullPath: '/paintings'
      preLoaderRoute: typeof PaintingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paintings/$slug': {
      id: '/paintings/$slug'
      path: '/$slug'
      fullPath: '/paintings/$slug'
      preLoaderRoute: typeof PaintingsSlugRouteImport
      parentRoute: typeof PaintingsRoute
    }
  }
}

interface PaintingsRouteChildren {
  PaintingsSlugRoute: typeof PaintingsSlugRoute
}

const PaintingsRouteChildren: PaintingsRouteChildren = {
  PaintingsSlugRoute: PaintingsSlugRoute,
}

const PaintingsRouteWithChildren = PaintingsRoute._addFileChildren(
  PaintingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  PaintingsRoute: PaintingsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
